[default_apps]
terminal="kitty"
[debug]
try_surpress_errors=true
try_surpress_warnings=false
[appearance]
width=900
height=593
gsk_renderer="cairo"
recolor_icons=false
icon_paths=["~/.config/sherlock/icons"]

