[default_apps]
terminal                =   "kitty"                         # Used to start applications
[debug]
try_surpress_errors     =   true                            # Disables the error screen for errors
try_surpress_warnings   =   false                           # Disables the error screen for warnings
[appearance]
width                   =   900                             # Sets the width of the main window
height                  =   593                             # Sets the height of the main window
gsk_renderer            =   "cairo"                         # Sets the rendering engine. [ngl, cairo, ]
recolor_icons           =   false                           # If set to true, uses the [icon-name]-symbolic icons
icon_paths              =   ["~/.config/sherlock/icons"]    # Sets where the application should look for custom icons

